### ISSUE TITLE
default ssl cipher suite prevents google from indexing pages

### ISSUE THREAD

**Issue by tkellen** [bocoup/deployment-workflow#46]
Our allowed cipher suite for TLS is so restrictive that googlebot can't crawl it. We currently allow the following:
AES256+EECDH & AES256+EDH

Here's what googlebot supported as of Feb 2015 (hint: neither of those two are on it):
https://www.ssllabs.com/ssltest/viewClient.html?name=Googlebot&version=Feb%202015

The fix is simple. Uncomment this:
https://github.com/bocoup/deployment-workflow/blob/master/deploy/ansible/roles/nginx/templates/ssl_params#L16
...and comment this:
https://github.com/bocoup/deployment-workflow/blob/master/deploy/ansible/roles/nginx/templates/ssl_params#L13

**Comment by tkellen** [comment]
Actually, now I'm doubting myself here. I was just able to add https://bocoup.com to webmaster tools and successfully crawl with either ciphersuite.

Whatever the case, we're switching to the weaker set until I can perform a more thorough investigation.

**Comment by cowboy** [comment]
Ok, keep us posted!

**Comment by cowboy** [comment]
I have a few questions.

* Why do the numbers fluctuate to 553, 477, 563 between 7/12/15 and 8/2/15?
* Did anything specific change in the site the week of 8/2/15?
* Why has the count dropped in steps ever since 8/9/15 and not all at once?

**Comment by cowboy** [comment]
@tkellen this discussion might be better off on the Bocoup.com repo.
