### ISSUE TITLE
Possible visual styling improvements

### ISSUE THREAD

**Issue by cowboy** [bocoup/deployment-workflow#52]
* [x] Remove Bower
* [x] Add Bocoup colors / styling
* [x] Add Bocoup branding / logo
* [x] Design a table of contents / nav
* [x] Implement table of contents / nav
* [x] Fix nested list vertical spacing
* [x] Remove unnecessary first-line left padding in code blocks
* [x] Add spacing / design around header elements to better separate sections

**Comment by cowboy** [comment]
Note: the sidenav is currently implemented, but it should be auto-generated based on the parsed README. (@cowboy TODO)

**Comment by isaacdurazo** [comment]
@cowboy Nested lists have slightly smaller font than `<p>`. This is a style implemented in bocoup.com. Is that the issue you are referring to?

**Comment by cowboy** [comment]
@isaacdurazo nested lists appear to "hug" their parent list item.

In this example, "ensure users are synced" and "ensure user public keys are synced" are closer together than "ensure user public keys are synced" and "main.yml" but farther apart than "users.yml" and "ensure users are synced". I think the vertical spacing should be uniform.

![](https://i.gyazo.com/9a43a81b7c47b2248a50aaa7ce321689.png)

**Comment by cowboy** [comment]
The spacing inconsistency becomes apparent when the left padding is removed:

![](https://i.gyazo.com/bf9d4de9dc5246b1fa7b66d1cce8a0ee.png)

**Comment by cowboy** [comment]
This was closed by 98badd3173886eb30da17cdff5178beda1e2b1af
