### ISSUE TITLE
update to support ansible 2.0

### ISSUE THREAD

**Issue by tkellen** [bocoup/deployment-workflow#73]
the biggest change will be blocks:
http://docs.ansible.com/ansible/playbooks_blocks.html

**Comment by cowboy** [comment]
Has this been done? Once done, should we require Ansible 2.0+?

**Comment by tkellen** [comment]
Yes this has been done in #85, #84, #82, #81, #80, #76, #74, #72.

We should require Ansible 2.0. PR #88 is the first change that isn't compatible with both Ansible 1x and 2x.
