### ISSUE TITLE
ansible.cfg removed but not from docs

### ISSUE THREAD

**Issue by jennschiffer** [bocoup/deployment-workflow#92]
https://deployment-workflow.bocoup.com/#ansible-configuration-file

that section mentions the ansible.cfg file which was removed in #88. i would make a PR to remove the section but i wanted to make sure first that nothing would go in its place.

**Comment by tkellen** [comment]
You can remove it from the docs, we don't have a use for it any longer. Until https://github.com/ansible/ansible/issues/11175 lands, I wouldn't actively recommend not using it, even.

**Comment by tkellen** [comment]
I don't think we need to put that in the docs (telling folks not to use it), just saying the current semantics around how it works are really dumb.
