### ISSUE TITLE
ERROR! Syntax Error while loading YAML.

### ISSUE THREAD

**Issue by BillyZac** [bocoup/deployment-workflow#94]
When I clone the repo and run `vagrant up`, I see this error:

```
==> vagrant: Running provisioner: ansible...
    vagrant: Running ansible-playbook...
ERROR! Syntax Error while loading YAML.

The error appears to have been in '/Users/zac/work/deployment-workflow-2/deploy/ansible/roles/users/tasks/users.yml': line 12, column 38, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    state: "{{ item.state | default(omit) }}"
    shell: "{{ item.shell | default("/bin/bash") }}"
                                     ^ here
```

As a shot in the dark (I'm new to Ansible and Vagrant) I changed the double quotes around /bin/bash to single quotes, ran `vagrant destroy` and `vagrant up`. This fixed this particular error, but then I get other errors. I can post those as well, if it's helpful, but I thought I'd start here in case there's something I'm doing wrong on this step.

**Comment by tkellen** [comment]
Thanks for the heads up @BillyZac! I've addressed these issues in #95. If you run into any other issues, let me know!
